# Generated by Django 4.1.3 on 2023-03-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
